import Footer from "@/app/Components/Footer";
import Navbar from "@/app/Components/Navbar/Navbar";
import ThinkArqContactForm from "@/app/Components/ThinkArqContactForm";
import { Metadata } from "next";
import { Suspense } from "react";

export const metadata: Metadata = {
  title: "Contact Us | Think Arq - Think Build Disrupt",
  description: "Generated by Think Arq Studio",
  openGraph: {
    title: "Contact Us | Think Arq - Think Build Disrupt",
    description: "Generated by Think Arq Studio",
    url: `https://thinkarq.com/`,
    images: "/meta-images/think-arq.png",
  },
  twitter: {
    card: "summary_large_image",
    title: "Contact Us | Think Arq - Think Build Disrupt",
    description: "Generated by Think Arq Studio",
    images: "/meta-images/think-arq.png",
  },
};

export default function Home() {
  return (
    <div className="w-full h-full">
      <Navbar />

      <div className="pt-[110px]">
        <div className="think-arq-container">
          <Suspense>
            <ThinkArqContactForm />
          </Suspense>
        </div>
      </div>
      <div className="w-full">
        <Footer />
      </div>
    </div>
  );
}
